# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ContactTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  # Pods for ContactTracker

  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'

  target 'ContactTracker-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
